# rust/python_ffi/Cargo.toml

[package]
name = "quprs_python"   
version.workspace = true
edition.workspace = true
authors.workspace = true
publish.workspace = true

[lib]
name = "_pathsum_rust"   
crate-type = ["cdylib"] 

[dependencies]
pyo3 = { version = "0.21.2", features = ["extension-module", "abi3-py38"] }
pathsum = { path = "../pathsum" }