#.github/workflows/python-publish.yml

name: Build and Publish Python Package

# Workflow Triggers:
# 1. On push to any branch (e.g., main, feature/xyz): triggers build.
# 2. On push of tags starting with 'v' (e.g., v1.2.3): triggers build and publish.
# 3. On pull request to main branch: triggers build.
# 4. Manual trigger via GitHub Actions UI.
on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # --- Job 1: Build Cross-Platform Wheels ---
  # This job runs on all triggers and builds binary wheels for multiple platforms.
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: Install build dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y cmake build-essential libgmp-dev libmpfr-dev zlib1g-dev

      - name: Install build dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install gmp mpfr zlib cmake

      - name: Install build dependencies (Windows)
        if: runner.os == 'Windows'
        run: echo "No extra dependencies needed for Windows runner by default"

      - name: Install Hatch
        run: pip install hatch hatch-vcs

      - name: Build wheel
        run: hatch build

      - name: Upload wheel artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-wheels-${{ matrix.os }}
          path: dist/*.whl

  # --- Job 2: Build Source Distribution (Sdist) ---
  # This job runs on all triggers and builds the source distribution.
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Hatch
        run: pip install hatch hatch-vcs

      - name: Build sdist with Hatch
        run: hatch build -t sdist

      - name: Upload sdist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-sdist
          path: dist/*.tar.gz


  # --- Job 3: Publish to PyPI and Create GitHub Release ---
  # This job runs only when a 'v*' tag is pushed.
  # It publishes all built artifacts to PyPI and creates a GitHub Release.
  publish:
    name: Publish to PyPI and Create Release
    # 'needs' ensures this job runs only after all build jobs succeed.
    needs: [build_wheels, build_sdist]
    # Condition: Only run when a 'v*' tag is pushed.
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    # Uses PyPI Trusted Publishing (OIDC) for secure publishing.
    permissions:
      # id-token: write is required for OIDC Trusted Publishing.
      id-token: write
      # contents: write is required to create a GitHub Release.
      contents: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: dist-*
          merge-multiple: true

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ## 🚀 Release Notes
            * **📦 Version:** `${{ github.ref_name }}`
            * **🔗 PyPI Link:** https://pypi.org/project/QuPRS/${{ github.ref_name }}
            * 🛠️ This release was automatically generated by GitHub Actions.
          files: dist/*